bloom_history: BUGFIX enabled test as noinst_
test_bloom_history cannot be compiled right now, some definitions are
missing:

```
test_blooming_history.o: In function `test_is_from_prefix':
test_blooming_history.c:58: undefined reference to `is_from_prefix'
bloom_history_functions.o: In function `pthread_entry_upload':
bloom_history_functions.c:124: undefined reference to `stop'
bloom_history_functions.c:129: undefined reference to `MUTEX_TIMER_STOP'
bloom_history_functions.c:132: undefined reference to `UPLOAD_INTERVAL'
bloom_history_functions.c:133: undefined reference to `MUTEX_TIMER_STOP'
bloom_history_functions.c:133: undefined reference to `CV_TIMER_STOP'
bloom_history_functions.c:134: undefined reference to `MUTEX_TIMER_STOP'
bloom_history_functions.c:151: undefined reference to `MUTEX_BLOOM_SWAP'
bloom_history_functions.c:154: undefined reference to `MUTEX_BLOOM_SWAP'
bloom_history_functions.c:178: undefined reference to `MUTEX_TIMER_STOP'
bloom_history_functions.c:124: undefined reference to `stop'
collect2: error: ld returned 1 exit status
```